### ISSUE TITLE
Update done percentage based on estimated time

### ISSUE THREAD

**Issue by TeLiXj** [jkraemer/redmine_percent_done#3]
Hi! Could be possible to update done percentage when submit a new log time?
For example if you estimate 1h for your issue and add 30 minutes, it's updated percentage to 50%.

Thanks for your job! :)

**Comment by adrianobr** [comment]
That's not cool. An estimate of a task in 1 hour and the time released of 0.50 hours does not mean that the task is 50% ready. Since it could take 2 hours to complete. It breaks the concept of graphic burndow/burnup, loses the metric of agil.

**Comment by jkraemer** [comment]
I agree, this isn't something I'd consider useful in practice.
